### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [maltose-lab/nightingale#3]
Hi...
Came across your amazing project and i really love the whole idea and what the project is all about.
I am a logo/icon designer and I want to help create a logo/icon for your project as my Free contribution and my love to always help contribute to amazing open source projects.

Currently working on an idea concept already and i will update it here once it is done, so as to get your feedback on the design and also any tweaks or changes you might want to suit your needs.

Your response would be greatly appreciated...
Regards!

**Comment by rev-hikari** [comment]
Sorry, we don't currently have a plan to add logo to it.
